export const classes = {
    ref: 'link-primary',
    refInvalid: 'link-primary link-invalid',
    displayEquation: '',
    blockEnvironment: 'block-container',
    blockTitle: 'link-foreground',
    proof: 'proof',
    proofIntro: '',
    qed: 'qed',
    cite: '',
    citeNote: '',
    citeRef: 'link-primary',
    divisionTitle: 'link-foreground',
    tikz: 'tikz-container',
    figure: 'figure',
    figureCaption: 'figure-caption link-foreground',
} as const;